# Generated by Django 4.1.2 on 2022-11-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('ingreso', models.CharField(max_length=50)),
            ],
        ),
    ]
